### ISSUE TITLE
Potential for more minimalism

### ISSUE THREAD

**Issue by annevk** [tc39/proposal-structs#13]
I'm still curious about https://twitter.com/annevk/status/1433688193321291778. It seems to me that shared structs (or at least the additional restrictions they add) would be a strictly simpler starting point than having both shared and non-shared structs.

And when I look at the motivation I only see compelling cases for shared structs.

**Comment by takikawa** [comment]
> I think the two main problematic restrictions for using shared structs as non-shared structs are:
> [...]
> Shared structs will have lower performance than non-shared structs, because their implementation have to support concurrent access.

I think that this will be a big deal for the Wasm GC use case, in that better performance is a key motivation for wanting to compile to Wasm. If Wasm GC's JS API design forces lower performance when interacting with JS due to using shared structs, I don't think Wasm engine implementers would be happy with the design (nor the Wasm producers who are compiling to it).

(I do think concurrency will be important for Wasm GC structs in the future as well, but this will likely be in a while after the implementation of the existing non-concurrent GC is further along)

**Comment by syg** [comment]
Closing some old threads.

This proposal currently plans to go forward with both non-shared and shared structs. The use cases for non-shared structs are:

- Reflection for WasmGC structs
- "Defensible classes", as they have one-shot initialization, declaratively sealed, and have non-generic methods. This works around two (terrible) rough corners of ordinary classes: return override, partially initialized instances. With the rise of TypeScript, for codebases that don't do expandos on class instances and don't rely on instance methods being generic, these should be a drop-in replacement that give codebases more guarantees and better performance.
- Non-generic methods + sealed instances means better performance, as the `this` value is checked upon entry, and then property accesses in the method body can be guaranteed monomorphic on the holder.
